name: Atlanta Ink CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest
    # strategy:
    #   max-parallel: 4
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.7"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # - name: Download scraped data artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: scraped_data
      #     path: ./data
    
      - name: Run scraper
        run: |
          python main.py
        env:
          DATA_FILE: ${{ secrets.DATA_FILE }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - name: Upload scraped data
        uses: actions/upload-artifact@v3
        with:
          name: scraped_data
          path: ./data/scraped_data.json

  download:
    needs: scrape
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download scraped data artifact
        uses: actions/download-artifact@v3
        with:
          name: scraped_data
          path: ./data

      - name: List files in ./data directory
        run: ls -al ./data